spring:
  datasource:
    username: staffing_agency
    password: staffing_agency
    url:  jdbc:mysql://localhost:3306/staffing_agency
    
  jpa:
    hibernate:
      ddl-auto: none
    show-sql:  true  
    
  sql:
    init:
      mode: never 
    